name: planet-notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.2
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.1.0
  - boost-cpp=1.68.0
  - branca=0.3.1
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.14.12
  - cartopy=0.17.0
  - certifi=2019.3.9
  - cffi=1.12.2
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.0.4
  - cligj=0.5.0
  - cloudpickle=0.8.0
  - colorcet=1.0.0
  - cryptography=2.6.1
  - curl=7.64.0
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=1.1.4
  - dask-core=1.1.4
  - datashader=0.6.9
  - datashape=0.5.4
  - dbus=1.13.2
  - decorator=4.4.0
  - defusedxml=0.5.0
  - descartes=1.1.0
  - dialite=0.5.2
  - distributed=1.26.0
  - entrypoints=0.3
  - expat=2.2.5
  - fiona=1.8.6
  - flexx=0.4.1
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=2.4.0
  - geojson=2.4.1
  - geojsonio=0.0.3
  - geopandas=0.4.1
  - geos=3.7.1
  - geotiff=1.4.3
  - geoviews=1.6.2
  - geoviews-core=1.6.2
  - gettext=0.19.8.1
  - giflib=5.1.7
  - github3.py=1.3.0
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - holoviews=1.12.1
  - hvplot=0.4.0
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipyleaflet=0.10.0
  - ipython=7.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jwcrypto=0.6.0
  - kealib=1.4.10
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - libcurl=7.64.0
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgdal=2.4.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.2
  - libpng=1.6.36
  - libpq=11.2
  - libsodium=1.0.16
  - libspatialindex=1.9.0
  - libspatialite=4.3.0a
  - libssh2=1.8.1
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.26.0
  - locket=0.2.0
  - lxml=4.3.2
  - mapclassify=2.0.1
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.11
  - mkl_random=1.0.2
  - more-itertools=4.3.0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - munch=2.3.2
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ndg-httpsclient=0.5.1
  - netcdf4=1.4.3.2
  - networkx=2.2
  - notebook=5.7.6
  - numba=0.41.0
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openblas=0.3.3
  - openjpeg=2.3.0
  - openssl=1.1.1b
  - owslib=0.17.1
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.7.1
  - pandocfilters=1.4.2
  - param=1.8.2
  - parso=0.3.4
  - partd=0.3.9
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.3
  - pixman=0.34.0
  - planet=1.2.2
  - pluggy=0.9.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.2
  - proj4=5.2.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pscript=0.7.1
  - psutil=5.6.1
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.0
  - pyasn1=0.4.4
  - pycparser=2.19
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pyepsg=0.4.0
  - pygments=2.3.1
  - pykdtree=1.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pyproj=1.9.6
  - pyqt=5.6.0
  - pyrsistent=0.14.11
  - pyshp=2.1.0
  - pysocks=1.6.8
  - pytest=4.3.1
  - python=3.7.2
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyviz_comms=0.7.1
  - pywavelets=1.0.2
  - pyyaml=5.1
  - pyzmq=18.0.1
  - qt=5.6.3
  - qtconsole=4.4.3
  - rasterio=1.0.22
  - readline=7.0
  - requests=2.21.0
  - requests-futures=0.9.9
  - rtree=0.8.3
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=40.8.0
  - shapely=1.6.4
  - sip=4.18.1
  - six=1.12.0
  - snuggs=1.4.3
  - sortedcontainers=2.1.0
  - sqlite=3.26.0
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.1
  - tqdm=4.31.1
  - traitlets=4.3.2
  - traittypes=0.2.1
  - tzcode=2018g
  - uritemplate.py=3.0.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - webruntime=0.5.6
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xarray=0.12.0
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.4
  - zlib=1.2.11
  - pip:
    - overpass==0.6.1
